// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvakhriARmL6XtDjicm3r6wt93PPU7zlo',
    appId: '1:955312638100:web:e91aba8b3954341652cc81',
    messagingSenderId: '955312638100',
    projectId: 'chat-app2-f4830',
    authDomain: 'chat-app2-f4830.firebaseapp.com',
    storageBucket: 'chat-app2-f4830.appspot.com',
    measurementId: 'G-RWNZ52TZP5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAud3liXL0V38jVs6cYKw8iaJhBzCUq1XY',
    appId: '1:955312638100:android:3b81a8c0b2565bd652cc81',
    messagingSenderId: '955312638100',
    projectId: 'chat-app2-f4830',
    storageBucket: 'chat-app2-f4830.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX0e23uRIvIeAEqKwoX0imTnosITVdSkI',
    appId: '1:955312638100:ios:b4d3f0ff7c19918652cc81',
    messagingSenderId: '955312638100',
    projectId: 'chat-app2-f4830',
    storageBucket: 'chat-app2-f4830.appspot.com',
    iosClientId: '955312638100-hj9r78fmet9s3j8gfhi8tpgpeepm0ud3.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBX0e23uRIvIeAEqKwoX0imTnosITVdSkI',
    appId: '1:955312638100:ios:b4d3f0ff7c19918652cc81',
    messagingSenderId: '955312638100',
    projectId: 'chat-app2-f4830',
    storageBucket: 'chat-app2-f4830.appspot.com',
    iosClientId: '955312638100-hj9r78fmet9s3j8gfhi8tpgpeepm0ud3.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
